import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import "bootstrap/dist/css/bootstrap.min.css";
import Layout from "./components/Layout";
import NextLink from "next/link";

import data from "./api/database/data/data";
import dataApi from "./api/database/products.json";

export default function Home() {
  return (
    <>
      <Layout>
        <div className="container">
          <h2 className="pt-5 pb-4 text-center">All Products</h2>
          <div className="row g-3">
            {/* {data.products.map((product) => console.log(product, "first"))} */}
            {/* {dataApi.map((product) => console.log(product, "second"))} */}
            {data.products.map((product) => (
              <div key={product.id} className="col-md-4 ">
                <div className="product-card border ">
                  <NextLink href={`/product/${product.slug}`} passHref>
                    <div style={{ cursor: "pointer" }}>
                      {/* <img className="img-fluid" src={product.image} alt="" /> */}
                      <Image className="" src={product.image} alt="" height={300} width={1000} />
                      <h2 className="px-3">{product.category}</h2>
                    </div>
                  </NextLink>
                  <div className="px-3 pb-2">
                    <p>${product.price}</p>
                    <button className="product-btn">Add To Cart</button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </Layout>
    </>
    // <div className={styles.container}>
    //   <Head>
    //     <title>E-commerce</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <h2>Hello</h2>

    //   <h1 className="text-danger">Products </h1>
    // </div>
  );
}
